### ISSUE TITLE
Can't get .zip to properly load in Avorion/data/directory

### ISSUE THREAD

**Issue by Xiluym** [w00zla/avorion-fleetcontrol#1]
When asked, I copied over the new files. However, the mod won't load using command /fleetcontrol, at all.

Not sure if I messed something up, but I triple-checked and couldn't find a mistake from following your directions.

**Comment by w00zla** [comment]
I checked the ZIP of the release and its contents are actually fine! Really don't know what went wrong in your case ... make at first sure you did not extract the ZIP with creating a subfolder like "fleetcontrol_v04" ... if thats not the case please send me your log-files for analysis *(you can find them in folders "__%APPDATA%\Roaming\Avorion__" and "__%APPDATA%\Roaming\Avorion\galaxies\...__")*
