### ISSUE TITLE
[Suggestion] bind script to ship and MoveUI for UI management

### ISSUE THREAD

**Issue by ghost** [w00zla/avorion-fleetcontrol#3]
Dirty made a couple of mods that help with this, instead of having to do the command the script will be active on all ships. Also MoveUI could help to make the UI configurable and movable.

https://github.com/dirtyredz/ShipScriptLoader
https://github.com/dirtyredz/MoveUI

**Comment by w00zla** [comment]
its not as easy as it may seem to "convert" the mod without completely rewriting it!
several scripts are used, including player, UI- and non-UI entity scripts, and the GUI code is not compatible with MoveUI but makes up most of the codelines.

but iI will consider it ;)
